name: Laravel Code Quality Checks

on: [push, pull_request]

jobs:
  code-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Cache Composer Dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      # ✅ Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo
          coverage: none

      # ✅ Install Composer Dependencies
      - name: Install PHP dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      # ✅ Fetch Git Changes (Required for Diff-Based Checks)
      - name: Fetch Git History
        run: git fetch --prune --unshallow

      # ✅ Get Changed PHP Files
      - name: Get Changed PHP Files
        id: changed_files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only origin/main | grep '\.php$' || echo '')" >> $GITHUB_ENV

      # ✅ Auto-fix PHPCS Errors with PHPCBF (Only Changed Files)
      - name: Auto-fix PHPCS Errors
        if: env.CHANGED_FILES != ''
        run: echo "$CHANGED_FILES" | xargs -r ./vendor/bin/phpcbf --standard=PSR12

      # ✅ Run PHP Linter (Syntax Check, Only Changed Files)
      - name: Run PHP Linter (Syntax Check)
        if: env.CHANGED_FILES != ''
        run: echo "$CHANGED_FILES" | xargs -r php -l

      # ✅ Run PHP CodeSniffer (PHPCS, Only Changed Files)
      - name: Run PHP CodeSniffer (PHPCS)
        if: env.CHANGED_FILES != ''
        run: echo "$CHANGED_FILES" | xargs -r ./vendor/bin/phpcs --standard=PSR12
        continue-on-error: true  # ✅ Prevents stopping on errors

      # ✅ Run PHPStan (Static Analysis)
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --level=5 app/

      # ✅ Run PHP-CS-Fixer (Auto-Fix Formatting, Only Changed Files)
      - name: Run PHP-CS-Fixer
        if: env.CHANGED_FILES != ''
        run: echo "$CHANGED_FILES" | xargs -r ./vendor/bin/php-cs-fixer fix --verbose
        continue-on-error: true  # ✅ Prevents workflow failure

      # ✅ Show Git Status (Check for Auto-Fixed Files)
      - name: Show Git Status
        run: git status
