name: Laravel Code Quality Checks

on: [push, pull_request]

jobs:
  code-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Cache Composer Dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      # ✅ Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo
          coverage: none

      # ✅ Install Composer Dependencies
      - name: Install PHP dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      # ✅ Run PHPCBF (Auto-fix Code Issues Before Linting)
      - name: Auto-fix PHPCS Errors with PHPCBF
        run: |
          git diff --name-only origin/main | grep '\.php$' | xargs -r ./vendor/bin/phpcbf --standard=PSR12

      # ✅ Run PHP Linter (Check Syntax Only)
      - name: Run PHP Linter (Syntax Check)
        run: |
          git fetch origin main --depth=1
          git diff --name-only origin/main | grep '\.php$' | xargs -r php -l

      # ✅ Run PHPCS (Check Formatting Issues After Auto-fix)
      - name: Run PHP CodeSniffer (PHPCS) After Auto-fix
        run: |
          git diff --name-only origin/main | grep '\.php$' | xargs -r ./vendor/bin/phpcs --standard=PSR12
        continue-on-error: true  # ✅ Prevents stopping on errors

      # ✅ Run PHPStan (Static Analysis)
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --level=5 app/

      # ✅ Run PHP-CS-Fixer (Auto-Fix PHP Code Formatting)
      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --verbose

      # ✅ Show Git Status (Check for Auto-Fixed Files)
      - name: Show Git Status
        run: git status
