name: Laravel Code Quality Checks

on: [push, pull_request]

jobs:
  code-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hung workflows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full git history for proper diff checks

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo
          coverage: none
          tools: cs2pr  # Convert checkstyle to GitHub annotations

      - name: Install PHP dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      # Code Quality Checks
      - name: PHP Syntax Check
        run: find . -type f -name '*.php' -not -path './vendor/*' -exec php -l {} \;

      - name: PHP CodeSniffer (PSR12)
        run: ./vendor/bin/phpcs --standard=PSR12 --colors -p app/

      - name: PHPStan Analysis
        run: ./vendor/bin/phpstan analyse --memory-limit=2G --error-format=github
        env:
          PHPSTAN_RESULT_CACHE: /tmp/phpstan

      - name: PHP-CS-Fixer Check
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --config=.php-cs-fixer.dist.php