name: Laravel Code Quality Checks

on: [push, pull_request]

jobs:
  code-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run PHP Linter
        run: find . -type f -name "*.php" -exec php -l {} \;

      - name: Run PHP CodeSniffer (PHPCS)
        run: ./vendor/bin/phpcs --standard=PSR12 app/

      # ✅ Auto-fix PHPCS errors
      - name: Run PHPCBF to Fix PHPCS Errors
        run: ./vendor/bin/phpcbf --standard=PSR12 app/

      - name: Run PHPStan (Static Analysis)
        run: ./vendor/bin/phpstan analyse --level=5 app/

      # ✅ Auto-fix PHP code formatting issues
      - name: Run PHP-CS-Fixer (Fix Formatting)
        run: ./vendor/bin/php-cs-fixer fix --verbose

      # ✅ Show Git Status (Check for Auto-Fixed Files)
      - name: Show Git Status
        run: git status
